Django-Projects/Online Book store/mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name = 'myapp' # this id a namespacing

urlpatterns = [
    path('', views.index,name='index'),
    #book/123
    path('book/<int:book_id>', views.detail,name='detail'),
    path('add/',views.add_book,name='add_book'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),

]

Django-Projects/Online Book store/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from myapp import views
from .import settings
from  django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),


] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Django-Projects/Online Book store/mysite/myapp/models.py
from django.db import models

class Book(models.Model):

    def __str__(self):
        return self.name
    
    name = models.CharField(max_length=255)
    desc = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)  
    book_image = models.ImageField(default='default.jpg',upload_to='book_images/')

Django-Projects/Online Book store/mysite/myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'desc', 'book_image', 'price']

Django-Projects/Online Book store/mysite/myapp/views.py
from django.shortcuts import render,HttpResponse,redirect
from .models import Book
from .forms import BookForm

# Create your views here.

def index(request):
    book_list = Book.objects.all()
    context = {
        'book_list':book_list
    }
    return render(request,'myapp/index.html',context) 

def detail(request,book_id):
    book = Book.objects.get(id=book_id)
    return render(request,'myapp/detail.html',{'book':book})

def add_book(request):
    if request.method == "POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']  # or  book_image = request.FILES.get('book_image')

        book = Book(name=name,desc=desc,price=price,book_image=book_image)
        
        book.save()

    return render(request,'myapp/add_book.html')

def update(request,id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'myapp/edit.html',{'form':form,'book':book})

def delete(request,id):
    if request.method=="POST":
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
        
    return render(request,'myapp/delete.html')

Django-Projects/Online Book store/mysite/myapp/templates/myapp/add_book.html
<form action="" method="POST" enctype="multipart/form-data" class="mt-4">
    {% csrf_token %}
    
    <div class="form-group">
        <label for="name">Book Name</label>
        <input type="text" name="name" id="name" class="form-control" placeholder="Enter name of book" required>
    </div><br>

    <div class="form-group">
        <label for="desc">Book Description</label>
        <input type="text" name="desc" id="desc" class="form-control" placeholder="Enter book description" required>
    </div><br>

    <div class="form-group">
        <label for="price">Book Price</label>
        <input type="number" name="price" id="price" class="form-control" placeholder="Enter book price" required>
    </div><br>

    <div class="form-group">
        <label for="book_image">Book Image</label>
        <input type="file" name="book_image" id="book_image" class="form-control-file">
    </div><br>

    <button type="submit" name="submit" class="btn btn-primary">Submit</button>
</form>

Django-Projects/Online Book store/mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css"
      integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N"
      crossorigin="anonymous"
    />
    <link rel="stylesheet" href="{% static 'myapp/css/index.css' %}" />

    <title>Document</title>
  </head>
  <body>
    <nav class="navbar navbar-dark bg-dark">
      <a class="navbar-brand" href="#"> Online Book Store </a>
      <a class="btn btn-primary" href="{% url 'myapp:add_book' %}">Add Book</a>
    </nav>

    {% block body %}

    {% endblock %}
  </body>
</html>

Django-Projects/Online Book store/mysite/myapp/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    Are u sure you want to delete this book?
    <input type="submit">
    
</form>

Django-Projects/Online Book store/mysite/myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %} 
{% block body %} 

<div class="container mt-4">
    <div class="row">
        <div class="col-md-4">
            <img width="100" height="100" src="{{ book.book_image.url }}" alt="{{ book.name }}" class="img-thumbnail">
        </div>
        <div class="col-md-8">
            <h2>Book Name: {{ book.name }}<br /></h2>
            <h4>Description: {{ book.desc }}<br /></h4>
            <h6>Price: ${{ book.price }}<br /></h6>
            
            <a class="btn btn-warning" href="{% url 'myapp:update' book.id %}">Update</a>
            <a class="btn btn-danger" href="{% url 'myapp:delete' book.id %}">Delete</a>
        </div>
    </div>
</div>

{% endblock body %}

Django-Projects/Online Book store/mysite/myapp/templates/myapp/edit.html
<form method="POST" enctype="multipart/form-data" >
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="" id="">
</form>

Django-Projects/Online Book store/mysite/myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        {% for book in book_list %}
        <div class="col-md-3">
            <div class="card">
                <img width="90" height="275" src="{{ book.book_image.url }}" class="card-img-top" alt="{{ book.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ book.name }}</h5>
                    <p class="card-text">${{ book.price }}</p>
                    <a class="btn btn-primary" href="{% url 'myapp:detail' book.id %}">View Details</a><br />
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock body %}